// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace PublisherBooks.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20260809163924_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BookId");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<Guid>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2343c3e6-a2db-4b5c-87af-e7e0605d816a"),
                            Genre = "Literary fiction",
                            PageCount = 312,
                            PublisherId = new Guid("8c76b8a8-f748-4eed-b13b-5ce2ba50ce18"),
                            ReleaseYear = 2018,
                            Title = "The Quiet Harbour"
                        },
                        new
                        {
                            Id = new Guid("f9d3ab49-d925-4e8c-b380-7c60b444b94a"),
                            Genre = "History",
                            PageCount = 448,
                            PublisherId = new Guid("8c76b8a8-f748-4eed-b13b-5ce2ba50ce18"),
                            ReleaseYear = 2021,
                            Title = "Patterns of the North"
                        },
                        new
                        {
                            Id = new Guid("66fdae8f-eb22-487a-8def-a138928f205b"),
                            Genre = "Mystery",
                            PageCount = 264,
                            PublisherId = new Guid("c67499e0-0041-4ee3-98b1-b2fdf6834885"),
                            ReleaseYear = 2019,
                            Title = "Winter Lantern"
                        },
                        new
                        {
                            Id = new Guid("1e0ef065-7153-4555-b23d-242e27bc4cbf"),
                            Genre = "Poetry",
                            PageCount = 190,
                            PublisherId = new Guid("c67499e0-0041-4ee3-98b1-b2fdf6834885"),
                            ReleaseYear = 2023,
                            Title = "Concrete and Rain"
                        },
                        new
                        {
                            Id = new Guid("800dfb90-d562-4595-9878-6ff361456cd0"),
                            Genre = "Historical fiction",
                            PageCount = 526,
                            PublisherId = new Guid("2dddc208-8925-41c4-80ec-bb58ee833dc7"),
                            ReleaseYear = 2020,
                            Title = "The Cartographer's Debt"
                        },
                        new
                        {
                            Id = new Guid("b0d5912d-d356-4dd9-b783-a95625c8a528"),
                            Genre = "Science",
                            PageCount = 358,
                            PublisherId = new Guid("2dddc208-8925-41c4-80ec-bb58ee833dc7"),
                            ReleaseYear = 2022,
                            Title = "Southern Reef"
                        });
                });

            modelBuilder.Entity("Entities.Models.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PublisherId");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8c76b8a8-f748-4eed-b13b-5ce2ba50ce18"),
                            City = "Manchester",
                            Country = "United Kingdom",
                            Name = "Northwind Press"
                        },
                        new
                        {
                            Id = new Guid("c67499e0-0041-4ee3-98b1-b2fdf6834885"),
                            City = "Toronto",
                            Country = "Canada",
                            Name = "Silverleaf Publishing"
                        },
                        new
                        {
                            Id = new Guid("2dddc208-8925-41c4-80ec-bb58ee833dc7"),
                            City = "Melbourne",
                            Country = "Australia",
                            Name = "Aurora Books"
                        });
                });

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.HasOne("Entities.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Entities.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
